### ISSUE TITLE
Replace mask_prefix and mask selector with MaskExtractor

### ISSUE THREAD

**Issue by A-Huli** [TheLion-ai/UMIE_datasets#67]
### Description
We currently have 2 args that are used for the same purpose.
Both **mask_selector** and **mask_prefix** args specify a substring that helps us identify if a given path points to a mask or an image. However, each of them is used in different steps.
**mask_selector** is a better name for this arg since the substring may not necessarily be a prefix.

We also have **img_prefix** that helps us identify paths pointing to an image. Let's rename this parameter to **img_selector** to match the same convention.

### What to do
1. Remove **mask_selector** from `base/step.py`. Rename **img_prefix** with **img_selector**.
2. Remove **mask_selector** PipelineArgs in `base/pipeline.py`. Rename **img_prefix** with **img_selector**.
3. Look for the `steps/` that use **img_prefix** and **mask_prefix**. Rename them.
4. Look for the `pipelines/` that use **img_prefix** and **mask_prefix**. Rename them.

### Expected behavior
We gave 1 PipelineArg for selecting imgs based on path, and another for selecting masks. Their names are **img_selector** and **mask_selector**.

**Comment by andrekomor** [comment]
I think **mask_selector**, and **image_selector** should be Boolean functions, and not strings (simillar to ImgIdExtractor, etc.). Sometimes it is not possible to simply distinguish images and masks based on string containing some other string. Sometimes more sophisticated methods are needed.
